#!/bin/sh


start() {
        /sbin/scull_load
        /sbin/faulty_load faulty
        modprobe hello
}

stop() {
        rmmod hello
        /sbin/faulty_unload faulty
        /sbin/scull_unload
}

case "$1" in
        start|stop)
                "$1";;
        *)
                echo "Usage: $0 {start|stop}"
                exit 1
esac
