#! /bin/sh
set -e

NAME=lddmodules
case "$1" in
	start)
		echo "Loading drivers and modules"
		/bin/aesdchar_load
		/bin/faulty_load faulty
		/bin/scull_load
		modprobe hello
		;;
	stop)
		echo "Unloading drivers and modules"
		rmmod hello
		/bin/aesdchar_unload
        	/bin/module_unload faulty
        	/bin/scull_unload
        	;;
    *)
        echo "Usage: $0 {start|stop}"
    exit 1
esac
exit 0
